### ISSUE TITLE
RPNG: RangeError: Overflow: input needs wider integers to process

### ISSUE THREAD

**Issue by nokome** [stencila/encoda#154]
When attempting to create an rPNG for a (largish) document (this repo's README):

```
npx ts-node --files src/cli convert README.md --to rpng temp.png --theme eLife --debug
🐛 DEBUG encoda:html Generating <html> element with options {"format":"html","filePath":"temp.png","isStandalone":true,"isBundle":false,"theme":"eLife"}
🐛 DEBUG encoda:puppeteer Launching new browser
🐛 DEBUG encoda:puppeteer Browser launched. pid: 21322
🚨 ERROR encoda:cli Overflow: input needs wider integers to process
  RangeError: Overflow: input needs wider integers to process
    at error (punycode.js:42:8)
    at Object.encode (punycode.js:335:4)
    at insert (/home/nokome/stencila/source/encoda/src/codecs/rpng/index.ts:86:50)
    at Object.exports.encode (/home/nokome/stencila/source/encoda/src/codecs/rpng/index.ts:219:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
🐛 DEBUG encoda:puppeteer Closing browser. pid: 21322
🐛 DEBUG encoda:puppeteer Browser closed
```

Note that the same error occurs if `--theme eLife --debug` options are dropped.

**Comment by nokome** [comment]
Another `punycode` related error:
```bash
npx ts-node --files src/cli "convert" "temp.docx" "temp.md"

🚨 ERROR encoda Maximum call stack size exceeded
  RangeError: Maximum call stack size exceeded
    at Object.decode (/home/nokome/stencila/source/encoda/node_modules/punycode/punycode.js:277:16)
    at find (/home/nokome/stencila/source/encoda/src/codecs/rpng/index.ts:192:33)
    at RPNGCodec.sniffDecodeSync (/home/nokome/stencila/source/encoda/src/codecs/rpng/index.ts:110:27)
    at decodeInline (/home/nokome/stencila/source/encoda/src/codecs/pandoc/index.ts:746:27)
    at Array.map (<anonymous>)
    at decodeInlines (/home/nokome/stencila/source/encoda/src/codecs/pandoc/index.ts:702:18)
    at decodePara (/home/nokome/stencila/source/encoda/src/codecs/pandoc/index.ts:470:19)
    at decodeBlock (/home/nokome/stencila/source/encoda/src/codecs/pandoc/index.ts:401:14)
    at blocks.map.block (/home/nokome/stencila/source/encoda/src/codecs/pandoc/index.ts:383:30)
    at Array.map (<anonymous>)
```
