### ISSUE TITLE
Error when packaged as binary

### ISSUE THREAD

**Issue by nokome** [stencila/encoda#258]
When this package is `pkg`ed up in the `stencila` CLI we get this error:

```bash
> ./bin/stencila convert README.md README.docx
⚠ WARN  encoda Timed out waiting for sync-rpc server to start (it should respond with "pong" when sent "ping"):

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/home/nokome/stencila/source/stencila/-e'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)


  Error: Timed out waiting for sync-rpc server to start (it should respond with "pong" when sent "ping"):

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/home/nokome/stencila/source/stencila/-e'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)


    at waitForAlive (/snapshot/stencila/node_modules/sync-rpc/lib/index.js:80:11)
    at start (/snapshot/stencila/node_modules/sync-rpc/lib/index.js:40:3)
    at sendMessage (/snapshot/stencila/node_modules/sync-rpc/lib/index.js:117:17)
    at createClient (/snapshot/stencila/node_modules/sync-rpc/lib/index.js:157:27)
    at Object.<anonymous> (/snapshot/stencila/node_modules/sync-request/lib/index.js:16:14)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
⚠ WARN  encoda No codec could be found for content "README.docx". Falling back to plain text codec.
```

whereas this works fine:

```bash
npx ts-node src/cli convert README.md README.docx
```

The same error report [here](https://github.com/zeit/pkg/issues/741) also suggests this is related to `pkg`ing. The `sync-rpc` package seems to be associated with `sync-request` (peer dependency?) which is deprecated ("N.B. You should not be using this in a production application...") and brought in by `citation-js` for making synchronous requests. Will first try to patch `citation-js` so that it does not use `sync-request`.

**Comment by Fuadk** [comment]
Hello,
I have the same issue when packaging. 
Is there is a solution for this issue?
Regards,
Fuad

**Comment by nokome** [comment]
Hi @Fuadk . This was our particular fix to this particular error https://github.com/stencila/encoda/commit/8fb9d5bfdcfacad939c6fab981f8c81da624c4a2. Is your question related to this repo or another?

**Comment by smartm0use** [comment]
Hello, sorry for this post but this place is the one in which a package that have sync-rpc among dependencies has fixed its issue.
Anyone can help me about the timeout sync-rpc error with another package that have sync-rpc among dependencies?

https://github.com/vercel/pkg/issues/204#issuecomment-1173093090
