### ISSUE TITLE
GDoc: throws an error if `horizontalRule ` present

### ISSUE THREAD

**Issue by beneboy** [stencila/encoda#89]
Error: Unhandled element type {"startIndex":68,"endIndex":69,"horizontalRule":{"textStyle":{}}}
    at parseParagraphElement (/snapshot/convert/dist/gdoc.js:426:15)
    at para.elements.map.node (/snapshot/convert/dist/gdoc.js:215:45)
    at Array.map (<anonymous>)
    at parseParagraph (/snapshot/convert/dist/gdoc.js:215:33)
    at doc.body.content.map (/snapshot/convert/dist/gdoc.js:144:24)
    at Array.map (<anonymous>)
    at parseDocument (/snapshot/convert/dist/gdoc.js:142:14)
    at Object.parse (/snapshot/convert/dist/gdoc.js:52:12)
    at parse (/snapshot/convert/dist/index.js:147:21)

**Comment by beneboy** [comment]
[example.txt](https://github.com/stencila/encoda/files/3256118/example.txt)

**Comment by nokome** [comment]
Thanks for reporting this. I think this will be addressed by https://github.com/stencila/encoda/pull/86.
